"""Slide 16: QR code to https://source.coop/epoch, ink on cream, as inline SVG.

    uv run --project scripts python scripts/gen_s16_qr.py

Writes slides/_gen/s16-qr.qmd (a raw-HTML partial). One path, crisp edges.
"""

from pathlib import Path

import qrcode

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "slides" / "_gen" / "s16-qr.qmd"
URL = "https://source.coop/epoch"
INK, CREAM = "#0A1628", "#F4F1EA"
QUIET = 2  # modules; the slide's cream ground supplies the rest


def main() -> None:
    qr = qrcode.QRCode(error_correction=qrcode.constants.ERROR_CORRECT_M, border=0)
    qr.add_data(URL)
    qr.make(fit=True)
    m = qr.get_matrix()
    n = len(m)
    size = n + 2 * QUIET
    d = []
    for y, row in enumerate(m):
        x = 0
        while x < n:
            if row[x]:
                start = x
                while x < n and row[x]:
                    x += 1
                d.append(f"M{start + QUIET},{y + QUIET}h{x - start}v1h-{x - start}z")
            else:
                x += 1
    svg = (
        f'<svg class="s16-qr-svg" viewBox="0 0 {size} {size}" shape-rendering="crispEdges" '
        f'role="img" aria-label="QR code: {URL}">'
        f'<rect width="{size}" height="{size}" fill="{CREAM}"/>'
        f'<path fill="{INK}" d="{"".join(d)}"/></svg>'
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(f"```{{=html}}\n<!-- generated by scripts/gen_s16_qr.py; do not edit -->\n{svg}\n```\n")
    print(f"QR version {qr.version}, {n}x{n} modules; wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
