"""Slide 2: the "minimal visibility" funnel, as an inline SVG partial.

Five tiers left to right (Brand -> Manufacturer -> Trader -> Mill -> Farm). Each
tier has more nodes than the last and is drawn more transparently, so the farm
tier almost disappears. Tiers fade in ~1.5 s apart (styles/s02.scss, --d).
No logos, no customer names.

    uv run --project scripts python scripts/gen_s02_funnel.py
"""

import random
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "slides" / "_gen" / "s02-funnel.qmd"

W, H = 1600, 640
CY = 285
XS = [170, 480, 790, 1100, 1410]  # tier centres
NAMES = ["Brand", "Manufacturer", "Trader", "Mill", "Farm"]
OPACITY = [1.0, 0.7, 0.42, 0.2, 0.07]  # nodes, edges and band
LABEL_OPACITY = [1.0, 0.85, 0.7, 0.58, 0.46]  # names stay readable
DELAY = [0.6, 2.1, 3.6, 5.1, 6.6]  # seconds
BOUNDS = [40, 325, 635, 945, 1255, 1565]  # band segment edges
HALF = [62, 100, 160, 212, 255, 270]  # band half-height at each edge
GAP = 10


def nodes() -> list[list[tuple[float, float, float]]]:
    rng = random.Random(7)
    tiers: list[list[tuple[float, float, float]]] = []
    tiers.append([(XS[0], CY, 34)])
    # Manufacturer: 3, Trader: 6 in a column
    for t, n, r in [(1, 3, 20), (2, 6, 15)]:
        half = (HALF[t] + HALF[t + 1]) / 2 - 38
        tiers.append([(XS[t], CY - half + 2 * half * i / (n - 1), r) for i in range(n)])
    # Mill: 12 in two staggered columns
    mill = []
    half = (HALF[3] + HALF[4]) / 2 - 34
    for i in range(12):
        x = XS[3] + (-34 if i % 2 == 0 else 34)
        mill.append((x, CY - half + 2 * half * i / 11, 12))
    tiers.append(mill)
    # Farm: 4 jittered columns x 11 rows
    farm = []
    half = (HALF[4] + HALF[5]) / 2 - 28
    for c in range(4):
        for i in range(11):
            x = XS[4] - 96 + 64 * c + rng.uniform(-10, 10)
            y = CY - half + 2 * half * (i + (0.5 if c % 2 else 0)) / 11.5 + rng.uniform(-6, 6)
            farm.append((x, y, 8))
    tiers.append(farm)
    return tiers


def edges(tiers):
    rng = random.Random(11)
    out: list[list[tuple[float, float, float, float]]] = [[]]
    for t in range(1, len(tiers)):
        parents = tiers[t - 1]
        segs = []
        for x, y, _ in tiers[t]:
            ranked = sorted(parents, key=lambda p: abs(p[1] - y))
            picks = [ranked[0]]
            if len(ranked) > 1 and rng.random() < 0.35:
                picks.append(ranked[1])
            for px, py, _ in picks:
                segs.append((px, py, x, y))
        out.append(segs)
    return out


def curve(x1, y1, x2, y2) -> str:
    mx = (x1 + x2) / 2
    return f"M{x1:.1f},{y1:.1f} C{mx:.1f},{y1:.1f} {mx:.1f},{y2:.1f} {x2:.1f},{y2:.1f}"


def main() -> None:
    tiers = nodes()
    links = edges(tiers)
    parts = [
        f'<svg class="s02-svg" viewBox="0 0 {W} {H}" role="img" '
        'aria-label="Five supply-chain tiers from brand to farm; each tier has more nodes and '
        'is fainter, until the farms are barely visible">'
    ]
    for t in range(5):
        x0, x1 = BOUNDS[t] + (GAP / 2 if t else 0), BOUNDS[t + 1] - (GAP / 2 if t < 4 else 0)
        h0, h1 = HALF[t], HALF[t + 1]
        band = (
            f"M{x0},{CY - h0} L{x1},{CY - h1} L{x1},{CY + h1} L{x0},{CY + h0} Z"
        )
        o = OPACITY[t]
        sw = [4, 3.5, 3, 2.5, 2][t]
        g = [f'<g class="s02-tier" style="--d:{DELAY[t]}s">']
        g.append(f'<g opacity="{o}">')
        g.append(f'<path class="s02-band" d="{band}"/>')
        if links[t]:
            g.append(f'<g class="s02-edges" stroke-width="{sw}">')
            g += [f'<path d="{curve(*s)}"/>' for s in links[t]]
            g.append("</g>")
        g.append('<g class="s02-nodes">')
        g += [f'<circle cx="{x:.1f}" cy="{y:.1f}" r="{r}"/>' for x, y, r in tiers[t]]
        g.append("</g></g>")
        g.append(
            f'<text class="s02-name" x="{XS[t]}" y="{H - 22}" text-anchor="middle" '
            f'opacity="{LABEL_OPACITY[t]}">{NAMES[t]}</text>'
        )
        g.append("</g>")
        parts += g
    parts.append("</svg>")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "<!-- Generated by scripts/gen_s02_funnel.py; do not edit by hand. -->\n"
        "```{=html}\n" + "\n".join(parts) + "\n```\n"
    )
    print(OUT.relative_to(ROOT), sum(len(t) for t in tiers), "nodes")


if __name__ == "__main__":
    main()
